name: Hello World

on:
  push:


env:
  GITHUB_TOKEN_CCI: ${{ secrets.GITHUB_TOKEN }}


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Run a one-line script
      run: echo "Hello, World!"

    - name: Install GitHub CLI
      run: |
        curl -L https://github.com/cli/cli/releases/download/v2.2.0/gh_2.2.0_linux_amd64.deb -o gh.deb
        sudo dpkg -i gh.deb
        rm gh.deb

    - name: Create GitHub Issue
      run: |
        echo $GITHUB_TOKEN_CCI | gh auth login --with-token
        gh issue create --title "Your Custom Issue Title" --body "This issue was created by GitHub Actions."
