name: Run Apex Unit Tests

on:
  push:


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Install sfdx with npm
      run: |
        npm i @salesforce/cli --global

    - name: Store SFDX Auth URL In File
      run: |
        echo ${{ secrets.PLAYGROUND_FORCE_URL }} > sfdxauth.txt

    - name: Add SFDX Org
      run: |
        sf force auth sfdxurl store -f sfdxauth.txt -a org

    - name: Run Apex Unit Tests
      run: |
        sf force apex test run -r human -c --wait 10 -o org
